import { ingestOracleRows } from "./oracle-ingest";
import type { OracleRow } from "./oracle";

export interface Env { DB: D1Database; ASSETS: Fetcher; IMPORT_TOKEN?: string; }
type TeamStats={id:number;name:string;games:number;wins:number;winRate:number;gd15:number|null;xp15:number|null;cs15:number|null;kda:number|null;firstBlood:number|null;firstTower:number|null;dragons:number|null;barons:number|null;vision:number|null;blueRate:number|null;redRate:number|null};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json","cache-control":"no-store"}});

async function stats(db:D1Database,id:number){return db.prepare(`SELECT t.id,t.name,COUNT(s.match_id) games,SUM(s.won) wins,AVG(s.won) winRate,AVG(s.gold_diff_15) gd15,AVG(s.xp_diff_15) xp15,AVG(s.cs_diff_15) cs15,AVG(CAST(s.kills+s.assists AS REAL)/NULLIF(s.deaths,0)) kda,AVG(s.first_blood) firstBlood,AVG(s.first_tower) firstTower,AVG(s.dragons) dragons,AVG(s.barons) barons,AVG(s.vision_score_per_minute) vision,AVG(CASE WHEN s.side='blue' THEN s.won END) blueRate,AVG(CASE WHEN s.side='red' THEN s.won END) redRate FROM teams t JOIN team_game_stats s ON s.team_id=t.id WHERE t.id=? GROUP BY t.id,t.name`).bind(id).first<TeamStats>();}
function relative(a:number|null,b:number|null){return a===null||b===null?null:(a-b)/(Math.abs(a)+Math.abs(b)+1);}
function predict(a:TeamStats,b:TeamStats){const fields:[string,number|null,number|null,number][]=[["Win rate",a.winRate,b.winRate,.25],["Gold diff @15",a.gd15,b.gd15,.18],["XP diff @15",a.xp15,b.xp15,.12],["CS diff @15",a.cs15,b.cs15,.08],["KDA",a.kda,b.kda,.10],["First blood",a.firstBlood,b.firstBlood,.07],["First tower",a.firstTower,b.firstTower,.06],["Dragons / game",a.dragons,b.dragons,.05],["Barons / game",a.barons,b.barons,.04],["Vision / min",a.vision,b.vision,.03],["Side win rate",((a.blueRate??0)+(a.redRate??0))/2,((b.blueRate??0)+(b.redRate??0))/2,.02]];const factors=fields.map(([name,av,bv,weight])=>({name,edge:relative(av,bv),weight}));const available=factors.filter(x=>x.edge!==null),weight=available.reduce((n,x)=>n+x.weight,0);const score=weight?available.reduce((n,x)=>n+(x.edge??0)*x.weight/weight,0)*2.8:0,probabilityA=1/(1+Math.exp(-score));return{teamA:a.name,teamB:b.name,probabilityA,probabilityB:1-probabilityA,confidence:Math.min(1,Math.min(a.games,b.games)/30)*weight,activeWeight:weight,factors};}

export default {async fetch(request:Request,env:Env){const url=new URL(request.url);if(url.pathname==="/api/health")return json({ok:true,source:"Oracle's Elixir",coverage:"2020+"});if(url.pathname==="/api/admin/oracle/rows"&&request.method==="POST"){if(!env.IMPORT_TOKEN||request.headers.get("authorization")!==`Bearer ${env.IMPORT_TOKEN}`)return json({error:"Unauthorized"},401);const body=await request.json() as {year?:number;sourceUrl?:string;rows?:OracleRow[]};if(!body.year||body.year<2020||!body.sourceUrl||!Array.isArray(body.rows)||body.rows.length<1||body.rows.length>500)return json({error:"Expected a 2020+ year, source URL, and 1-500 rows."},400);await env.DB.prepare("INSERT INTO oracle_import_runs(source_year,source_url,status,started_at) VALUES(?,?, 'running', CURRENT_TIMESTAMP) ON CONFLICT(source_year) DO UPDATE SET source_url=excluded.source_url,status='running'").bind(body.year,body.sourceUrl).run();const result=await ingestOracleRows(env.DB,body.rows);await env.DB.prepare("UPDATE oracle_import_runs SET rows_received=rows_received+?,rows_rejected=rows_rejected+? WHERE source_year=?").bind(result.accepted,result.rejected,body.year).run();return json(result);}if(url.pathname==="/api/import/status"){const {results}=await env.DB.prepare("SELECT source_year,status,rows_received,rows_rejected,source_url FROM oracle_import_runs ORDER BY source_year DESC").all();return json({source:"Oracle's Elixir",coverage:"2020+",imports:results});}if(url.pathname==="/api/teams"){const {results}=await env.DB.prepare("SELECT t.id,t.name,COUNT(s.match_id) games FROM teams t JOIN team_game_stats s ON s.team_id=t.id GROUP BY t.id,t.name HAVING games>0 ORDER BY t.name").all();return json(results);}if(url.pathname==="/api/matchup"){const a=Number(url.searchParams.get("teamA")),b=Number(url.searchParams.get("teamB"));if(!Number.isInteger(a)||!Number.isInteger(b)||a===b)return json({error:"Select two distinct teams."},400);const [teamA,teamB]=await Promise.all([stats(env.DB,a),stats(env.DB,b)]);if(!teamA||!teamB)return json({error:"Both teams need imported Oracle’s Elixir statistics."},404);return json(predict(teamA,teamB));}return env.ASSETS.fetch(request);}} satisfies ExportedHandler<Env>;
