import { parseGolGame } from "./gol-parser";
import { ingestOracleRows } from "./oracle-ingest";
import type { OracleRow } from "./oracle";

export interface Env { DB: D1Database; ASSETS: Fetcher; IMPORT_ENABLED: string; IMPORT_TOKEN?: string; }
type TeamRow = { id:number; name:string; games:number; wins:number; win_rate:number; gd15:number; xp15:number; cs15:number; kd:number; first_blood:number; first_tower:number; vision:number; blue_rate:number; red_rate:number };
type ImportJob = { id:number; kind:"season"|"tournament"|"series"|"game"; source_key:string; source_url:string; tournament_id:number|null };
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json","cache-control":"public, max-age=300"}});
const sourceHeaders={"user-agent":"LoLStatsPredictor/0.1 (personal statistics project; low-rate importer)",accept:"text/html,application/json"};
const clean=(value:string)=>value.replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/<[^>]*>/g,"").trim();
const gol=(path:string)=>`https://gol.gg${path.startsWith("/")?path:`/${path}`}`;

async function teamStats(db:D1Database,teamId:number):Promise<TeamRow|null>{return db.prepare(`SELECT t.id,t.name,COUNT(s.match_id) games,SUM(s.won) wins,AVG(s.won) win_rate,AVG(s.gold_diff_15) gd15,AVG(s.xp_diff_15) xp15,AVG(s.cs_diff_15) cs15,AVG(s.kills-s.deaths) kd,AVG(s.first_blood) first_blood,AVG(s.first_tower) first_tower,AVG(s.vision_score_per_minute) vision,AVG(CASE WHEN s.side='blue' THEN s.won END) blue_rate,AVG(CASE WHEN s.side='red' THEN s.won END) red_rate FROM teams t JOIN team_game_stats s ON s.team_id=t.id WHERE t.id=? GROUP BY t.id,t.name`).bind(teamId).first<TeamRow>();}
function edge(a:number|null,b:number|null){return a==null||b==null?null:(a-b)/(Math.abs(a)+Math.abs(b)+(a===0||b===0?1:0));}
function probability(a:TeamRow,b:TeamRow){const metrics=[["Win rate",a.win_rate,b.win_rate,.25],["Gold diff @15",a.gd15,b.gd15,.16],["XP diff @15",a.xp15,b.xp15,.10],["CS diff @15",a.cs15,b.cs15,.08],["Kill-death diff",a.kd,b.kd,.12],["First blood",a.first_blood,b.first_blood,.08],["First tower",a.first_tower,b.first_tower,.07],["Vision / min",a.vision,b.vision,.06],["Blue/red side",((a.blue_rate??0)+(a.red_rate??0))/2,((b.blue_rate??0)+(b.red_rate??0))/2,.08]] as const;const factors=metrics.map(([name,av,bv,weight])=>({name,edge:edge(av,bv),weight}));const activeWeight=factors.reduce((sum,x)=>sum+(x.edge==null?0:x.weight),0);const score=activeWeight?factors.reduce((sum,x)=>sum+(x.edge==null?0:x.edge*x.weight/activeWeight),0)*2.4:0;const probabilityA=1/(1+Math.exp(-score));return{teamA:a.name,teamB:b.name,probabilityA,probabilityB:1-probabilityA,confidence:Math.min(1,Math.min(a.games,b.games)/20)*activeWeight,activeWeight,factors};}

async function enqueue(db:D1Database,kind:ImportJob["kind"],key:string,url:string,tournamentId:number|null=null){await db.prepare("INSERT OR IGNORE INTO import_jobs(kind,source_key,source_url,tournament_id) VALUES(?,?,?,?)").bind(kind,key,url,tournamentId).run();}
async function seed(db:D1Database){const existing=await db.prepare("SELECT COUNT(*) count FROM import_jobs").first<{count:number}>();if(existing?.count)return;for(let season=3;season<=16;season++)await enqueue(db,"season",`season:S${season}`,`https://gol.gg/tournament/ajax.trlist.php?season=S${season}`);}
async function importSeason(db:D1Database,job:ImportJob){const res=await fetch(job.source_url,{headers:sourceHeaders});if(!res.ok)throw Error(`Gol.gg returned ${res.status}`);const rows=await res.json() as Array<{trname:string;region?:string;nbgames?:number;firstgame?:string;lastgame?:string}>;const season=/S\d+/.exec(job.source_key)?.[0]??null;for(const row of rows){if(!row.trname)continue;const url=gol(`/tournament/tournament-matchlist/${encodeURIComponent(row.trname)}/`);await db.prepare("INSERT OR IGNORE INTO tournaments(gol_slug,name,season,region,games_count,first_game_date,last_game_date,source_url) VALUES(?,?,?,?,?,?,?,?)").bind(row.trname,row.trname,season,row.region??null,row.nbgames??null,row.firstgame??null,row.lastgame??null,url).run();const tournament=await db.prepare("SELECT id FROM tournaments WHERE gol_slug=?").bind(row.trname).first<{id:number}>();if(tournament)await enqueue(db,"tournament",`tournament:${row.trname}`,url,tournament.id);}}
async function importTournament(db:D1Database,job:ImportJob){const res=await fetch(job.source_url,{headers:sourceHeaders});if(!res.ok)throw Error(`Gol.gg returned ${res.status}`);const html=await res.text();for(const link of html.matchAll(/href=['"]\.\.\/game\/stats\/(\d+)\/page-(summary|game)\//g)){const kind=link[2]==="summary"?"series":"game";await enqueue(db,kind,`${kind}:${link[1]}`,gol(`/game/stats/${link[1]}/page-${link[2]}/`),job.tournament_id);}}
async function importSeries(db:D1Database,job:ImportJob){const res=await fetch(job.source_url,{headers:sourceHeaders});if(!res.ok)throw Error(`Gol.gg returned ${res.status}`);for(const link of (await res.text()).matchAll(/href=['"]\.\.\/game\/stats\/(\d+)\/page-game\//g))await enqueue(db,"game",`game:${link[1]}`,gol(`/game/stats/${link[1]}/page-game/`),job.tournament_id);}
async function importGame(db:D1Database,job:ImportJob){
  const res=await fetch(job.source_url,{headers:sourceHeaders});if(!res.ok)throw Error(`Gol.gg returned ${res.status}`);
  const html=await res.text(),gameId=Number(/game:(\d+)/.exec(job.source_key)?.[1]),parsed=parseGolGame(html),teams=parsed.teams;
  if(!gameId||teams.length!==2)throw Error("Could not identify both teams; source layout may have changed.");
  for(const team of teams)await db.prepare("INSERT OR IGNORE INTO teams(gol_id,name,source_url) VALUES(?,?,?)").bind(team.golId,team.name,gol(`/teams/team-stats/${team.golId}/split-ALL/tournament-ALL/`)).run();
  const ids=await Promise.all(teams.map(t=>db.prepare("SELECT id FROM teams WHERE gol_id=?").bind(t.golId).first<{id:number}>()));
  await db.prepare("INSERT OR IGNORE INTO matches(gol_game_id,tournament_id,blue_team_id,red_team_id,duration_seconds,source_url) VALUES(?,?,?,?,?,?)").bind(gameId,job.tournament_id,ids[0]?.id??null,ids[1]?.id??null,parsed.durationSeconds,job.source_url).run();
  const match=await db.prepare("SELECT id FROM matches WHERE gol_game_id=?").bind(gameId).first<{id:number}>();if(!match)return;
  const roles=["TOP","JUNGLE","MID","BOT","SUPPORT"];
  for(const [index,player] of parsed.players.entries()){const teamId=ids[player.teamIndex]?.id;if(!teamId)continue;await db.prepare("INSERT OR REPLACE INTO player_game_stats(match_id,team_id,player_name,role,champion,kills,deaths,assists,cs) VALUES(?,?,?,?,?,?,?,?,?)").bind(match.id,teamId,player.name,roles[index%5]??null,player.champion,player.kills,player.deaths,player.assists,player.cs).run();if(player.champion)await db.prepare("INSERT OR REPLACE INTO drafts(match_id,team_id,phase,sequence_no,champion) VALUES(?,?,?,?,?)").bind(match.id,teamId,"pick",index%5+1,player.champion).run();}
  for(const metric of parsed.metrics){const teamId=ids[metric.teamIndex]?.id;if(!teamId)continue;await db.prepare("INSERT OR REPLACE INTO game_metrics(match_id,team_id,player_name,metric,numeric_value) VALUES(?,?,?,?,?)").bind(match.id,teamId,metric.playerName,metric.metric,metric.value).run();}
  if(parsed.finalGoldDiff!==null&&parsed.finalGoldDiff!==0){for(let side=0;side<2;side++){const teamId=ids[side]?.id,players=parsed.players.filter(p=>p.teamIndex===side);if(!teamId||players.length!==5)continue;const won=(parsed.finalGoldDiff>0?0:1)===side?1:0;await db.prepare("INSERT OR REPLACE INTO team_game_stats(match_id,team_id,side,won,kills,deaths,assists,gold_diff_15,cs_diff_15,first_blood,first_tower,dragons,barons,heralds,towers) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(match.id,teamId,side===0?"blue":"red",won,players.reduce((n,p)=>n+p.kills,0),players.reduce((n,p)=>n+p.deaths,0),players.reduce((n,p)=>n+p.assists,0),side===0?parsed.goldDiff15:parsed.goldDiff15===null?null:-parsed.goldDiff15,null,parsed.firstBloodTeam===side?1:0,parsed.firstTowerTeam===side?1:0,parsed.dragons[side],parsed.barons[side],parsed.heralds[side],parsed.towers[side]).run();}}
}
async function runImport(env:Env){if(env.IMPORT_ENABLED!=="true")return;await seed(env.DB);const job=await env.DB.prepare("SELECT id,kind,source_key,source_url,tournament_id FROM import_jobs WHERE status='pending' ORDER BY id LIMIT 1").first<ImportJob>();if(!job)return;await env.DB.prepare("UPDATE import_jobs SET status='running',attempts=attempts+1 WHERE id=?").bind(job.id).run();try{if(job.kind==="season")await importSeason(env.DB,job);else if(job.kind==="tournament")await importTournament(env.DB,job);else if(job.kind==="series")await importSeries(env.DB,job);else await importGame(env.DB,job);await env.DB.prepare("UPDATE import_jobs SET status='complete',completed_at=CURRENT_TIMESTAMP,last_error=NULL WHERE id=?").bind(job.id).run();}catch(error){await env.DB.prepare("UPDATE import_jobs SET status=CASE WHEN attempts>=3 THEN 'failed' ELSE 'pending' END,last_error=? WHERE id=?").bind(String(error).slice(0,500),job.id).run();}}

export default {async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);if(url.pathname==="/api/health")return json({ok:true});if(url.pathname==="/api/admin/oracle/rows"&&request.method==="POST"){if(!env.IMPORT_TOKEN||request.headers.get("authorization")!==`Bearer ${env.IMPORT_TOKEN}`)return json({error:"Unauthorized"},401);const body=await request.json() as {year?:number;sourceUrl?:string;rows?:OracleRow[]};if(!body.year||!body.sourceUrl||!Array.isArray(body.rows)||body.rows.length>500)return json({error:"Expected year, sourceUrl, and 1-500 rows."},400);await env.DB.prepare("INSERT INTO oracle_import_runs(source_year,source_url,status,started_at) VALUES(?,?, 'running', CURRENT_TIMESTAMP) ON CONFLICT(source_year) DO UPDATE SET source_url=excluded.source_url,status='running',started_at=COALESCE(oracle_import_runs.started_at,CURRENT_TIMESTAMP)").bind(body.year,body.sourceUrl).run();const result=await ingestOracleRows(env.DB,body.rows);await env.DB.prepare("UPDATE oracle_import_runs SET rows_received=rows_received+?,rows_rejected=rows_rejected+? WHERE source_year=?").bind(result.accepted,result.rejected,body.year).run();return json(result);}if(url.pathname==="/api/import/status"){const [{results:legacy},{results:oracle}]=await Promise.all([env.DB.prepare("SELECT status,COUNT(*) count FROM import_jobs GROUP BY status ORDER BY status").all(),env.DB.prepare("SELECT source_year,status,rows_received,rows_rejected FROM oracle_import_runs ORDER BY source_year DESC").all()]);return json({enabled:env.IMPORT_ENABLED==="true",jobs:legacy,oracle});}if(url.pathname==="/api/teams"){const {results}=await env.DB.prepare("SELECT id,name,region FROM teams ORDER BY name").all();return json(results);}if(url.pathname==="/api/matchup"){const a=Number(url.searchParams.get("teamA")),b=Number(url.searchParams.get("teamB"));if(!Number.isInteger(a)||!Number.isInteger(b)||a===b)return json({error:"Select two different teams."},400);const [teamA,teamB]=await Promise.all([teamStats(env.DB,a),teamStats(env.DB,b)]);if(!teamA||!teamB)return json({error:"Both teams need imported game statistics."},404);return json(probability(teamA,teamB));}return env.ASSETS.fetch(request);},async scheduled(_controller:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil(runImport(env));}} satisfies ExportedHandler<Env>;
